version: '2'
services:
  heatbeat:
    restart: always
    image: jscheel42/heatbeat
    command: foreground
    ports:
      - "4000:4000"
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
